__schema__ = "waterch.tasker.launcher.Launcher"
__name__ = "Knowledge distillation on mHealth by ResNet"
__author__ = "Chen Runze"
__version__ = "0.0.1"
__email__ = "chenrz925@bupt.edu.cn"
__abstract__ = ""

# ----- Global settings -----

[__setting__]
    [__setting__.storage]
    reference = "tasker.storage.DictStorage"
    [__setting__.log]
        [__setting__.log.console]
        class = 'logging.StreamHandler'
        formatter = 'default'
        level = 'INFO'
        stream = 'ext://sys.stdout'
        [__setting__.log.file]
        class = 'logging.FileHandler'
        formatter = 'default'
        level = 'DEBUG'
        filename = '.tasker/log/mhelth-kd-resnet.log'

# ----- Task metainfo -----

[[__meta__]]
reference = "tasker.tasks.utils.SetEnvironmentTask"
include = false
path = ""
profile = "env"
execute = true

[[__meta__]]
reference = "datasets.mhealth.MHealthDataLoaderTask:train"
include = false
path = ""
profile = "train_loader"
execute = true

[[__meta__]]
reference = "datasets.mhealth.MHealthDataLoaderTask:validate"
include = false
path = ""
profile = "validate_loader"
execute = true

[[__meta__]]
reference = "models.har_kd.kd.ResNetTeacherTrainTask:teacher"
include = false
path = ""
profile = "teacher_model"
execute = true

[[__meta__]]
reference = "models.har_kd.kd.ResNetStudentTrainTask:student"
include = false
path = ""
profile = "student_model"
execute = true

# ----- task profiles -----

[env]
env = [
    ["CUDA_VISIBLE_DEVICES", "7"]
]

[train_loader]
sampler_type = "none"
    [train_loader.dataset]
    reference = "datasets.mhealth.MHealth"
        [train_loader.dataset.kwargs]
        root_dir = "/public/lhy/crz/datasets/mhealth"
        num_workers = 0
        window_size = 250
        window_stride = 50
        filter_type = 'if_not'
        filter_by = ['subject9', 'subject10']
        preprocess = ['robust']
    [train_loader.loader]
    batch_size = 256
    shuffle = true
    num_workers = 4
    pin_memory = true
    drop_last = false

[validate_loader]
sampler_type = "none"
    [validate_loader.dataset]
    reference = "datasets.mhealth.MHealth"
        [validate_loader.dataset.kwargs]
        root_dir = "/public/lhy/crz/datasets/mhealth"
        num_workers = 0
        window_size = 250
        window_stride = 50
        filter_type = 'if'
        filter_by = ['subject9', 'subject10']
        preprocess = ['robust']
    [validate_loader.loader]
    batch_size = 256
    shuffle = true
    num_workers = 4
    pin_memory = true
    drop_last = false

[teacher_model]
device = "cuda:0"
non_blocking = false
max_epochs = 70
    [teacher_model.model]
    in_channels = 23
    block = "bottleneck" # "bottleneck" or "basic_block"
    layers = [2, 3, 2, 2]
    channels = [32, 64, 128, 64]
    num_classes = 12 # 12 class from mhealth dataset
    zero_init_residual = false
    groups = 1
    width_per_group = 64
    [teacher_model.optimizer]
    reference = "torch.optim.AdamW"
        [teacher_model.optimizer.kwargs]
        lr = 1e-4
        amsgrad = true
        [teacher_model.loss]
        reference = "torch.nn.CrossEntropyLoss"
            [teacher_model.loss.kwargs]

[student_model]
device = "cuda:0"
non_blocking = false
max_epochs = 400
    [student_model.model]
    in_channels = 23
    block = "bottleneck" # "bottleneck" or "basic_block"
    layers = [1, 1, 1]
    channels = [32, 48, 64]
    num_classes = 12 # 12 class from mhealth dataset
    zero_init_residual = false
    groups = 2
    width_per_group = 32
    [student_model.optimizer]
    reference = "torch.optim.AdamW"
        [student_model.optimizer.kwargs]
        lr = 1e-4
        amsgrad = true
        [student_model.loss]
        ratio = 1.0
        temperature = 1.0